#!/usr/bin/env python3
"""Small stdio MCP server for Claude Code <-> Codex collaboration."""

import argparse
import contextlib
import datetime as dt
import fcntl
import json
import os
from pathlib import Path, PurePosixPath
import sys
import tempfile
import traceback


SERVER_NAME = "collaboration"
SERVER_VERSION = "0.1.0"


def utc_now():
    return dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()


class StateStore:
    def __init__(self, workspace):
        self.workspace = Path(workspace).resolve()
        self.agents_dir = self.workspace / ".agents"
        self.state_path = self.agents_dir / "state.json"
        self.lock_path = self.agents_dir / "state.lock"
        self.messages_path = self.agents_dir / "messages.md"
        self.tasks_path = self.agents_dir / "tasks.md"
        self.agents_dir.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def empty_state():
        return {"version": 1, "next_message_id": 1, "messages": [], "claims": {}}

    @contextlib.contextmanager
    def locked(self):
        with self.lock_path.open("a+", encoding="utf-8") as lock_file:
            fcntl.flock(lock_file.fileno(), fcntl.LOCK_EX)
            try:
                if self.state_path.exists():
                    with self.state_path.open(encoding="utf-8") as state_file:
                        state = json.load(state_file)
                else:
                    state = self.empty_state()
                yield state
                self._write_json_atomic(self.state_path, state)
                self._write_views(state)
            finally:
                fcntl.flock(lock_file.fileno(), fcntl.LOCK_UN)

    @staticmethod
    def _write_json_atomic(path, value):
        fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=str(path.parent))
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as output:
                json.dump(value, output, ensure_ascii=False, indent=2)
                output.write("\n")
            os.replace(temporary, path)
        finally:
            if os.path.exists(temporary):
                os.unlink(temporary)

    def _write_text_atomic(self, path, text):
        fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=str(path.parent))
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as output:
                output.write(text)
            os.replace(temporary, path)
        finally:
            if os.path.exists(temporary):
                os.unlink(temporary)

    def _write_views(self, state):
        message_lines = ["# Agent messages", "", "Generated by collaboration MCP. Do not edit.", ""]
        if not state["messages"]:
            message_lines.append("No messages.")
        for message in state["messages"]:
            readers = ", ".join(message.get("read_by", [])) or "none"
            message_lines.extend([
                f"## #{message['id']} {message['from']} → {message['to']}",
                "",
                f"- Sent: {message['sent_at']}",
                f"- Read by: {readers}",
                "",
                message["message"],
                "",
            ])

        task_lines = ["# File claims", "", "Generated by collaboration MCP. Do not edit.", ""]
        if not state["claims"]:
            task_lines.append("No active claims.")
        for path, claim in sorted(state["claims"].items()):
            task_lines.extend([
                f"- `{path}` — **{claim['agent']}**; {claim.get('task') or 'no task description'}; claimed {claim['claimed_at']}"
            ])

        self._write_text_atomic(self.messages_path, "\n".join(message_lines).rstrip() + "\n")
        self._write_text_atomic(self.tasks_path, "\n".join(task_lines).rstrip() + "\n")


def require_text(arguments, name):
    value = arguments.get(name)
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{name} must be a non-empty string")
    return value.strip()


def normalize_path(workspace, raw_path):
    if not isinstance(raw_path, str) or not raw_path.strip():
        raise ValueError("every path must be a non-empty string")
    candidate = PurePosixPath(raw_path.replace("\\", "/"))
    if candidate.is_absolute():
        resolved = Path(str(candidate)).resolve()
    else:
        resolved = (workspace / Path(*candidate.parts)).resolve()
    try:
        relative = resolved.relative_to(workspace)
    except ValueError as error:
        raise ValueError(f"path is outside the workspace: {raw_path}") from error
    normalized = relative.as_posix()
    if normalized in ("", "."):
        raise ValueError("claiming the entire workspace is not allowed")
    return normalized


def paths_overlap(left, right):
    left_parts = PurePosixPath(left).parts
    right_parts = PurePosixPath(right).parts
    shorter = min(len(left_parts), len(right_parts))
    return left_parts[:shorter] == right_parts[:shorter]


class CollaborationTools:
    def __init__(self, workspace):
        self.store = StateStore(workspace)

    def send_message(self, arguments):
        sender = require_text(arguments, "from_agent")
        recipient = require_text(arguments, "to_agent")
        message_text = require_text(arguments, "message")
        with self.store.locked() as state:
            message = {
                "id": state["next_message_id"],
                "from": sender,
                "to": recipient,
                "message": message_text,
                "sent_at": utc_now(),
                "read_by": [],
            }
            state["next_message_id"] += 1
            state["messages"].append(message)
        return {"sent": message}

    def read_messages(self, arguments):
        agent = require_text(arguments, "agent")
        unread_only = arguments.get("unread_only", True)
        mark_read = arguments.get("mark_read", True)
        if not isinstance(unread_only, bool) or not isinstance(mark_read, bool):
            raise ValueError("unread_only and mark_read must be booleans")
        with self.store.locked() as state:
            messages = []
            for message in state["messages"]:
                addressed = message["to"] in (agent, "*", "all")
                unread = agent not in message.get("read_by", [])
                if addressed and (unread or not unread_only):
                    messages.append(dict(message))
                    if mark_read and unread:
                        message.setdefault("read_by", []).append(agent)
            if mark_read:
                for result in messages:
                    if agent not in result.get("read_by", []):
                        result.setdefault("read_by", []).append(agent)
        return {"agent": agent, "messages": messages, "count": len(messages)}

    def claim_task(self, arguments):
        agent = require_text(arguments, "agent")
        task = require_text(arguments, "task")
        raw_paths = arguments.get("paths")
        if not isinstance(raw_paths, list) or not raw_paths:
            raise ValueError("paths must be a non-empty array")
        paths = sorted(set(normalize_path(self.store.workspace, path) for path in raw_paths))
        with self.store.locked() as state:
            conflicts = []
            for requested in paths:
                for claimed_path, claim in state["claims"].items():
                    if claim["agent"] != agent and paths_overlap(requested, claimed_path):
                        conflicts.append({"requested_path": requested, "claimed_path": claimed_path, **claim})
            if conflicts:
                return {"claimed": False, "paths": [], "conflicts": conflicts}
            timestamp = utc_now()
            for path in paths:
                state["claims"][path] = {"agent": agent, "task": task, "claimed_at": timestamp}
        return {"claimed": True, "paths": paths, "conflicts": []}

    def release_task(self, arguments):
        agent = require_text(arguments, "agent")
        raw_paths = arguments.get("paths")
        if raw_paths is not None and not isinstance(raw_paths, list):
            raise ValueError("paths must be an array when provided")
        with self.store.locked() as state:
            if raw_paths is None:
                paths = [path for path, claim in state["claims"].items() if claim["agent"] == agent]
            else:
                paths = sorted(set(normalize_path(self.store.workspace, path) for path in raw_paths))
            released = []
            not_owned = []
            for path in paths:
                claim = state["claims"].get(path)
                if claim and claim["agent"] == agent:
                    del state["claims"][path]
                    released.append(path)
                elif claim:
                    not_owned.append({"path": path, **claim})
        return {"released": released, "not_owned": not_owned}

    def get_status(self, arguments):
        agent = arguments.get("agent")
        if agent is not None and (not isinstance(agent, str) or not agent.strip()):
            raise ValueError("agent must be a non-empty string when provided")
        if isinstance(agent, str):
            agent = agent.strip()
        with self.store.locked() as state:
            claims = [{"path": path, **claim} for path, claim in sorted(state["claims"].items())]
            unread = []
            if agent:
                unread = [
                    message for message in state["messages"]
                    if message["to"] in (agent, "*", "all") and agent not in message.get("read_by", [])
                ]
            return {
                "workspace": str(self.store.workspace),
                "claims": claims,
                "claim_count": len(claims),
                "message_count": len(state["messages"]),
                "agent": agent,
                "unread_count": len(unread) if agent else None,
                "unread_messages": unread if agent else [],
            }

    def call(self, name, arguments):
        handlers = {
            "send_message": self.send_message,
            "read_messages": self.read_messages,
            "claim_task": self.claim_task,
            "release_task": self.release_task,
            "get_status": self.get_status,
        }
        if name not in handlers:
            raise ValueError(f"unknown tool: {name}")
        return handlers[name](arguments or {})


TOOLS = [
    {
        "name": "send_message",
        "description": "Send a durable message to another agent or to '*' for all agents.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "from_agent": {"type": "string"},
                "to_agent": {"type": "string"},
                "message": {"type": "string"},
            },
            "required": ["from_agent", "to_agent", "message"],
            "additionalProperties": False,
        },
    },
    {
        "name": "read_messages",
        "description": "Read messages addressed to an agent and optionally mark them as read.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "agent": {"type": "string"},
                "unread_only": {"type": "boolean", "default": True},
                "mark_read": {"type": "boolean", "default": True},
            },
            "required": ["agent"],
            "additionalProperties": False,
        },
    },
    {
        "name": "claim_task",
        "description": "Atomically claim repository-relative files or directories before editing them.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "agent": {"type": "string"},
                "task": {"type": "string"},
                "paths": {"type": "array", "items": {"type": "string"}, "minItems": 1},
            },
            "required": ["agent", "task", "paths"],
            "additionalProperties": False,
        },
    },
    {
        "name": "release_task",
        "description": "Release selected claims owned by an agent, or all its claims when paths is omitted.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "agent": {"type": "string"},
                "paths": {"type": "array", "items": {"type": "string"}},
            },
            "required": ["agent"],
            "additionalProperties": False,
        },
    },
    {
        "name": "get_status",
        "description": "Return current file claims and, when agent is supplied, its unread messages.",
        "inputSchema": {
            "type": "object",
            "properties": {"agent": {"type": "string"}},
            "additionalProperties": False,
        },
    },
]


def result_payload(value):
    rendered = json.dumps(value, ensure_ascii=False, indent=2)
    return {"content": [{"type": "text", "text": rendered}], "structuredContent": value}


def handle_request(tools, request):
    method = request.get("method")
    request_id = request.get("id")
    if method == "initialize":
        requested = request.get("params", {}).get("protocolVersion", "2025-06-18")
        return {
            "jsonrpc": "2.0",
            "id": request_id,
            "result": {
                "protocolVersion": requested,
                "capabilities": {"tools": {"listChanged": False}},
                "serverInfo": {"name": SERVER_NAME, "version": SERVER_VERSION},
                "instructions": "Check get_status/read_messages before work, claim paths before edits, then send a handoff and release claims.",
            },
        }
    if method == "ping":
        return {"jsonrpc": "2.0", "id": request_id, "result": {}}
    if method == "tools/list":
        return {"jsonrpc": "2.0", "id": request_id, "result": {"tools": TOOLS}}
    if method == "tools/call":
        params = request.get("params") or {}
        try:
            value = tools.call(params.get("name"), params.get("arguments") or {})
            result = result_payload(value)
        except Exception as error:
            result = {"content": [{"type": "text", "text": str(error)}], "isError": True}
        return {"jsonrpc": "2.0", "id": request_id, "result": result}
    if method == "shutdown":
        return {"jsonrpc": "2.0", "id": request_id, "result": None}
    if request_id is None:
        return None
    return {
        "jsonrpc": "2.0",
        "id": request_id,
        "error": {"code": -32601, "message": f"Method not found: {method}"},
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--workspace", required=True)
    args = parser.parse_args()
    tools = CollaborationTools(args.workspace)

    for line in sys.stdin:
        if not line.strip():
            continue
        try:
            request = json.loads(line)
            response = handle_request(tools, request)
            if response is not None:
                sys.stdout.write(json.dumps(response, ensure_ascii=False) + "\n")
                sys.stdout.flush()
        except Exception:
            traceback.print_exc(file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
